# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 524)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ButtonDisplay = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonDisplay.sizePolicy().hasHeightForWidth())
        self.ButtonDisplay.setSizePolicy(sizePolicy)
        self.ButtonDisplay.setMinimumSize(QtCore.QSize(200, 100))
        self.ButtonDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.ButtonDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonDisplay.setObjectName("ButtonDisplay")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ButtonDisplay)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_3 = QtWidgets.QToolButton(self.ButtonDisplay)
        self.toolButton_3.setMinimumSize(QtCore.QSize(50, 30))
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout.addWidget(self.toolButton_3)
        self.toolButton = QtWidgets.QToolButton(self.ButtonDisplay)
        self.toolButton.setMinimumSize(QtCore.QSize(50, 30))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout.addWidget(self.ButtonDisplay)
        self.OCRTextDisplay = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OCRTextDisplay.sizePolicy().hasHeightForWidth())
        self.OCRTextDisplay.setSizePolicy(sizePolicy)
        self.OCRTextDisplay.setMinimumSize(QtCore.QSize(100, 100))
        self.OCRTextDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.OCRTextDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OCRTextDisplay.setObjectName("OCRTextDisplay")
        self.verticalLayout.addWidget(self.OCRTextDisplay)
        self.ScreenShotDisplay = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.ScreenShotDisplay.sizePolicy().hasHeightForWidth())
        self.ScreenShotDisplay.setSizePolicy(sizePolicy)
        self.ScreenShotDisplay.setMinimumSize(QtCore.QSize(100, 100))
        self.ScreenShotDisplay.setAutoFillBackground(True)
        self.ScreenShotDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.ScreenShotDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ScreenShotDisplay.setObjectName("ScreenShotDisplay")
        self.verticalLayout.addWidget(self.ScreenShotDisplay)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_3.setText(_translate("MainWindow", "开始实时截图"))
        self.toolButton.setText(_translate("MainWindow", "停止实时截图"))
